import fs from "node:fs";
import path from "node:path";
import { finish, issue, readYamlFile, resolveConventionsRoot, writeYamlFile, type Issue } from "./lib/common.js";

const SCRIPT_ID = "generate-final-mission-report";
const root = resolveConventionsRoot();
const issues: Issue[] = [];
const manifestPath = path.join(root, ".ai", "reports", "evidence-manifest.yaml");

let evidenceManifest: any = { entries: [] };
if (!fs.existsSync(manifestPath)) {
  issues.push(issue("critical", "EVIDENCE_MANIFEST_MISSING", "Cannot generate final mission report without evidence-manifest.yaml; run collect_evidence first."));
} else {
  evidenceManifest = readYamlFile(manifestPath);
  if (evidenceManifest.artifact !== "evidence_manifest_v2" || evidenceManifest.schema_version !== "2.0") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_SCHEMA_INVALID", "Final mission report requires evidence_manifest_v2 schema_version 2.0.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (evidenceManifest.generated_by !== "collect-evidence") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_NOT_SCRIPT_PRODUCED", "Final mission report requires an evidence manifest generated by collect-evidence.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!evidenceManifest.manifest_validation || typeof evidenceManifest.manifest_validation !== "object") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_MISSING", "Evidence manifest must include manifest_validation universal result.", ".ai/reports/evidence-manifest.yaml"));
  } else if (evidenceManifest.manifest_validation.blocking === true || ["failed", "blocked"].includes(String(evidenceManifest.manifest_validation.status ?? ""))) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_FAILED", "Evidence manifest validation is blocking or failed.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!Array.isArray(evidenceManifest.entries)) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRIES_INVALID", "Evidence manifest entries must be a list.", ".ai/reports/evidence-manifest.yaml"));
    evidenceManifest.entries = [];
  }
}

const entries = Array.isArray(evidenceManifest.entries) ? evidenceManifest.entries : [];
const counts: Record<string, number> = {};
for (const entry of entries) {
  const type = String(entry?.source_type ?? "unknown");
  counts[type] = (counts[type] ?? 0) + 1;
  if (entry?.manifest_entry_schema !== "evidence_manifest_v2_entry") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRY_SCHEMA_INVALID", `Evidence entry must use evidence_manifest_v2_entry: ${String(entry?.path ?? "unknown")}`));
  }
  if (typeof entry?.content_sha256 !== "string" || !/^[a-f0-9]{64}$/.test(entry.content_sha256)) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRY_HASH_INVALID", `Evidence entry must include content_sha256: ${String(entry?.path ?? "unknown")}`));
  }
}

const blockingStatuses = new Set(["fail", "failed", "blocked"]);
const blockingEvidence = entries.filter((entry: any) => entry?.blocking === true || blockingStatuses.has(String(entry?.status ?? "").toLowerCase()));
const scoreDecisionEvidence = entries.filter((entry: any) => entry?.source_type === "scoring" && entry?.score_decision);
const scoreDecisionBlocking = scoreDecisionEvidence.filter((entry: any) => entry?.score_decision?.blocking_decision === true);
const revisionLoopEvidence = entries.filter((entry: any) => entry?.source_type === "revision" && entry?.revision_loop_analysis);
const revisionLoopBlocking = revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.blocking_decision === true);
const safeStructureEvidence = entries.filter((entry: any) => entry?.source_type === "source_artifact" && entry?.safe_structure_analysis);
const safeStructureBlocking = safeStructureEvidence.filter((entry: any) => entry?.safe_structure_analysis?.blocking_decision === true);
const architectureQualityEvidence = entries.filter((entry: any) => entry?.source_type === "source_artifact" && entry?.architecture_quality_analysis);
const architectureQualityBlocking = architectureQualityEvidence.filter((entry: any) => entry?.architecture_quality_analysis?.blocking_decision === true);
function paths(list: any[]): string[] {
  return list.map((entry: any) => entry.path).filter((value: any) => typeof value === "string");
}
function claim(claim_id: string, claim_type: string, evidenceRefs: string[], claim_status = "supported", notApplicableReason?: string): any {
  return {
    claim_schema_version: "1.0",
    claim_id,
    claim_type,
    claim_status,
    support_mode: claim_status === "supported" ? "manifest_backed" : "not_applicable",
    evidence_refs: evidenceRefs,
    ...(notApplicableReason ? { not_applicable_reason: notApplicableReason } : {}),
  };
}
function optionalClaim(claim_id: string, claim_type: string, evidenceRefs: string[], notApplicableReason: string): any {
  return evidenceRefs.length
    ? claim(claim_id, claim_type, evidenceRefs)
    : claim(claim_id, claim_type, [], "not_applicable", notApplicableReason);
}
const allEvidenceRefs = paths(entries);
const reportClaims = [
  claim("evidence_manifest_validated", "manifest_integrity", allEvidenceRefs),
  optionalClaim("validation_summary_backed", "validation", paths(entries.filter((entry: any) => entry.source_type === "validation")), "No validation evidence entries were present in the evidence manifest."),
  optionalClaim("score_decision_summary_backed", "scoring", paths(scoreDecisionEvidence), "No score decision artifact was present in the evidence manifest."),
  optionalClaim("revision_loop_summary_backed", "revision", paths(revisionLoopEvidence), "No revision loop analysis artifact was present in the evidence manifest."),
  optionalClaim("safe_structure_summary_backed", "safe_structure", paths(safeStructureEvidence), "No safe structure analysis artifact was present in the evidence manifest."),
  optionalClaim("architecture_quality_summary_backed", "architecture_quality", paths(architectureQualityEvidence), "No architecture quality analysis artifact was present in the evidence manifest."),
  optionalClaim("transition_evidence_backed", "transition", paths(entries.filter((entry: any) => ["gate", "handoff", "revision"].includes(String(entry.source_type)))), "No gate, handoff, or revision transition evidence was present in the evidence manifest."),
];
const reportClaimsById = new Map(reportClaims.map((entry: any) => [String(entry.claim_id), entry]));
function claimBackedNarrativeSection(sectionId: string, title: string, sourceClaimId: string, supportedText: string, notApplicableText: string): any {
  const sourceClaim = reportClaimsById.get(sourceClaimId);
  const claimStatus = String(sourceClaim?.claim_status ?? "unsupported");
  const evidenceRefs = claimStatus === "supported" && Array.isArray(sourceClaim?.evidence_refs) ? sourceClaim.evidence_refs : [];
  return {
    section_schema_version: "1.0",
    section_id: sectionId,
    title,
    generated_from: "report_claim",
    source_claim_id: sourceClaimId,
    claim_status: claimStatus,
    support_mode: sourceClaim?.support_mode ?? null,
    evidence_refs: evidenceRefs,
    summary_text: claimStatus === "supported" ? supportedText : notApplicableText,
  };
}
const narrativeSummary = {
  narrative_schema_version: "1.0",
  generated_from_report_claims: true,
  freeform_narrative_allowed: false,
  sections: [
    claimBackedNarrativeSection("evidence_manifest", "Evidence manifest", "evidence_manifest_validated", `Final report is based on ${entries.length} manifest-backed evidence artifact(s).`, "Evidence manifest was not available for narrative summary generation."),
    claimBackedNarrativeSection("validation", "Validation evidence", "validation_summary_backed", `Validation summary is backed by ${counts.validation ?? 0} validation evidence artifact(s).`, "No validation evidence entries were present in the evidence manifest."),
    claimBackedNarrativeSection("score_decision", "Score decision evidence", "score_decision_summary_backed", `Score decision summary is backed by ${scoreDecisionEvidence.length} scoring artifact(s).`, "No score decision artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("revision_loop", "Revision loop evidence", "revision_loop_summary_backed", `Revision loop summary is backed by ${revisionLoopEvidence.length} revision analysis artifact(s).`, "No revision loop analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("safe_structure", "Safe structure evidence", "safe_structure_summary_backed", `Safe structure summary is backed by ${safeStructureEvidence.length} structure analysis artifact(s).`, "No safe structure analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("architecture_quality", "Architecture quality evidence", "architecture_quality_summary_backed", `Architecture quality summary is backed by ${architectureQualityEvidence.length} adapter-neutral architecture artifact(s).`, "No architecture quality analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("transition", "Transition evidence", "transition_evidence_backed", "Transition evidence summary is backed by gate, handoff, or revision artifacts.", "No gate, handoff, or revision transition evidence was present in the evidence manifest."),
  ],
};
const unsupportedReportClaims = reportClaims.filter((entry: any) => {
  if (entry.claim_status === "supported") return !Array.isArray(entry.evidence_refs) || entry.evidence_refs.length === 0;
  if (entry.claim_status === "not_applicable") return typeof entry.not_applicable_reason !== "string" || !entry.not_applicable_reason.trim();
  return true;
});
for (const unsupported of unsupportedReportClaims) {
  issues.push(issue("error", "REPORT_CLAIM_UNSUPPORTED", `Final report claim is unsupported or missing evidence: ${String(unsupported.claim_id ?? "unknown_claim")}`, ".ai/reports/final-mission-report.yaml"));
}
const finalReport = {
  artifact: "final_mission_report",
  generated_by: SCRIPT_ID,
  status: issues.length || blockingEvidence.length ? "blocked" : "complete",
  summary: "Final mission report generated from typed report_claims and validated evidence_manifest_v2 artifacts.",
  summary_source: "typed_report_claims",
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_index: ".ai/reports/evidence-index.yaml",
  evidence_refs: allEvidenceRefs,
  report_claim_schema: {
    schema_version: "1.0",
    unsupported_claim_policy: "block_report_validation",
    supported_claim_count: reportClaims.filter((entry: any) => entry.claim_status === "supported").length,
    not_applicable_claim_count: reportClaims.filter((entry: any) => entry.claim_status === "not_applicable").length,
    unsupported_claim_count: unsupportedReportClaims.length,
  },
  report_claims: reportClaims,
  narrative_summary: narrativeSummary,
  evidence_counts_by_type: counts,
  evidence_manifest_summary: {
    schema_version: evidenceManifest.schema_version ?? null,
    manifest_status: evidenceManifest.status ?? null,
    evidence_count: entries.length,
    validation_status: evidenceManifest.manifest_validation?.status ?? null,
    validation_blocking: evidenceManifest.manifest_validation?.blocking === true,
  },
  validation_summary: {
    blocking_evidence_count: blockingEvidence.length,
    failed_evidence_refs: paths(blockingEvidence),
    blocking_validation_refs: paths(blockingEvidence.filter((entry: any) => entry.source_type === "validation")),
  },
  score_decision_summary: {
    score_decision_refs: paths(scoreDecisionEvidence),
    score_decision_count: scoreDecisionEvidence.length,
    blocking_score_decision_refs: paths(scoreDecisionBlocking),
    observe_mode_only: scoreDecisionEvidence.every((entry: any) => entry?.score_decision?.blocking_decision !== true),
    recommendations: scoreDecisionEvidence.map((entry: any) => ({
      source: entry.path,
      mission_mode: entry.score_decision?.mission_mode ?? null,
      deterministic_recommendation: entry.score_decision?.deterministic_recommendation ?? null,
      blocking_decision: entry.score_decision?.blocking_decision === true,
    })),
  },
  revision_loop_summary: {
    revision_loop_refs: paths(revisionLoopEvidence),
    revision_loop_count: revisionLoopEvidence.length,
    blocking_revision_loop_refs: paths(revisionLoopBlocking),
    observe_mode_only: revisionLoopEvidence.every((entry: any) => entry?.revision_loop_analysis?.blocking_decision !== true),
    repeated_fingerprint_count: revisionLoopEvidence.reduce((total: number, entry: any) => total + Number(entry?.revision_loop_analysis?.repeated_fingerprint_count ?? 0), 0),
    no_progress_suspected_count: revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.no_progress_suspected === true).length,
    analyses: revisionLoopEvidence.map((entry: any) => ({
      source: entry.path,
      mission_id: entry.revision_loop_analysis?.mission_id ?? null,
      active_failure_fingerprint: entry.revision_loop_analysis?.active_failure_fingerprint ?? null,
      active_fingerprint_count: entry.revision_loop_analysis?.active_fingerprint_count ?? 0,
      no_progress_suspected: entry.revision_loop_analysis?.no_progress_suspected === true,
      blocking_decision: entry.revision_loop_analysis?.blocking_decision === true,
    })),
  },
  safe_structure_summary: {
    safe_structure_refs: paths(safeStructureEvidence),
    safe_structure_count: safeStructureEvidence.length,
    blocking_safe_structure_refs: paths(safeStructureBlocking),
    observe_mode_only: safeStructureEvidence.every((entry: any) => entry?.safe_structure_analysis?.blocking_decision !== true),
    total_inbound_dependency_count: safeStructureEvidence.reduce((total: number, entry: any) => total + Number(entry?.safe_structure_analysis?.inbound_dependency_count ?? 0), 0),
    warning_codes: Array.from(new Set(safeStructureEvidence.flatMap((entry: any) => Array.isArray(entry?.safe_structure_analysis?.warning_codes) ? entry.safe_structure_analysis.warning_codes : []))).sort(),
    analyses: safeStructureEvidence.map((entry: any) => ({
      source: entry.path,
      change_kind: entry.safe_structure_analysis?.change_kind ?? null,
      candidate_file: entry.safe_structure_analysis?.candidate_file ?? null,
      target_file: entry.safe_structure_analysis?.target_file ?? null,
      inbound_dependency_count: entry.safe_structure_analysis?.inbound_dependency_count ?? 0,
      outbound_dependency_count: entry.safe_structure_analysis?.outbound_dependency_count ?? 0,
      warning_codes: entry.safe_structure_analysis?.warning_codes ?? [],
      blocking_decision: entry.safe_structure_analysis?.blocking_decision === true,
    })),
  },
  architecture_quality_summary: {
    architecture_quality_refs: paths(architectureQualityEvidence),
    architecture_quality_count: architectureQualityEvidence.length,
    blocking_architecture_quality_refs: paths(architectureQualityBlocking),
    observe_mode_only: architectureQualityEvidence.every((entry: any) => entry?.architecture_quality_analysis?.blocking_decision !== true),
    adapter_neutral_core: architectureQualityEvidence.every((entry: any) => entry?.architecture_quality_analysis?.adapter_neutral === true),
    total_quality_dimension_count: architectureQualityEvidence.reduce((total: number, entry: any) => total + Number(entry?.architecture_quality_analysis?.quality_dimension_count ?? 0), 0),
    warning_codes: Array.from(new Set(architectureQualityEvidence.flatMap((entry: any) => Array.isArray(entry?.architecture_quality_analysis?.warning_codes) ? entry.architecture_quality_analysis.warning_codes : []))).sort(),
    analyses: architectureQualityEvidence.map((entry: any) => ({
      source: entry.path,
      adapter_discovery_source: entry.architecture_quality_analysis?.adapter_discovery_source ?? null,
      adapter_neutral: entry.architecture_quality_analysis?.adapter_neutral === true,
      language_adapter_count: entry.architecture_quality_analysis?.language_adapter_count ?? 0,
      framework_adapter_count: entry.architecture_quality_analysis?.framework_adapter_count ?? 0,
      quality_dimension_count: entry.architecture_quality_analysis?.quality_dimension_count ?? 0,
      warning_codes: entry.architecture_quality_analysis?.warning_codes ?? [],
      blocking_decision: entry.architecture_quality_analysis?.blocking_decision === true,
    })),
  },
  transition_evidence: {
    gates: paths(entries.filter((entry: any) => entry.source_type === "gate")),
    handoffs: paths(entries.filter((entry: any) => entry.source_type === "handoff")),
    revisions: paths(entries.filter((entry: any) => entry.source_type === "revision")),
  },
  unresolved_issues: blockingEvidence.map((entry: any) => ({ source: entry.path, status: entry.status, blocking: entry.blocking === true })),
};

writeYamlFile(path.join(root, ".ai", "reports", "final-mission-report.yaml"), finalReport);
writeYamlFile(path.join(root, ".ai", "reports", "mission-evidence-summary.yaml"), {
  artifact: "mission_evidence_summary",
  generated_by: SCRIPT_ID,
  status: finalReport.status,
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_counts_by_type: counts,
  evidence_manifest_summary: finalReport.evidence_manifest_summary,
  report_claim_count: finalReport.report_claims.length,
  narrative_summary_section_count: finalReport.narrative_summary.sections.length,
});

finish(SCRIPT_ID, issues, [".ai/reports/final-mission-report.yaml", ".ai/reports/mission-evidence-summary.yaml"], {
  status: finalReport.status,
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_count: entries.length,
});
