import fs from "node:fs";
import path from "node:path";
import { finish, issue, readYamlFile, resolveConventionsRoot, writeYamlFile, type Issue } from "./lib/common.js";

const SCRIPT_ID = "generate-final-mission-report";
const root = resolveConventionsRoot();
const issues: Issue[] = [];
const manifestPath = path.join(root, ".ai", "reports", "evidence-manifest.yaml");

let evidenceManifest: any = { entries: [] };
if (!fs.existsSync(manifestPath)) {
  issues.push(issue("critical", "EVIDENCE_MANIFEST_MISSING", "Cannot generate final mission report without evidence-manifest.yaml; run collect_evidence first."));
} else {
  evidenceManifest = readYamlFile(manifestPath);
  if (evidenceManifest.artifact !== "evidence_manifest_v2" || evidenceManifest.schema_version !== "2.0") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_SCHEMA_INVALID", "Final mission report requires evidence_manifest_v2 schema_version 2.0.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (evidenceManifest.generated_by !== "collect-evidence") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_NOT_SCRIPT_PRODUCED", "Final mission report requires an evidence manifest generated by collect-evidence.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!evidenceManifest.manifest_validation || typeof evidenceManifest.manifest_validation !== "object") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_MISSING", "Evidence manifest must include manifest_validation universal result.", ".ai/reports/evidence-manifest.yaml"));
  } else if (evidenceManifest.manifest_validation.blocking === true || ["failed", "blocked"].includes(String(evidenceManifest.manifest_validation.status ?? ""))) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_FAILED", "Evidence manifest validation is blocking or failed.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!Array.isArray(evidenceManifest.entries)) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRIES_INVALID", "Evidence manifest entries must be a list.", ".ai/reports/evidence-manifest.yaml"));
    evidenceManifest.entries = [];
  }
}

const entries = Array.isArray(evidenceManifest.entries) ? evidenceManifest.entries : [];
const counts: Record<string, number> = {};
for (const entry of entries) {
  const type = String(entry?.source_type ?? "unknown");
  counts[type] = (counts[type] ?? 0) + 1;
  if (entry?.manifest_entry_schema !== "evidence_manifest_v2_entry") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRY_SCHEMA_INVALID", `Evidence entry must use evidence_manifest_v2_entry: ${String(entry?.path ?? "unknown")}`));
  }
  if (typeof entry?.content_sha256 !== "string" || !/^[a-f0-9]{64}$/.test(entry.content_sha256)) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRY_HASH_INVALID", `Evidence entry must include content_sha256: ${String(entry?.path ?? "unknown")}`));
  }
}

const blockingStatuses = new Set(["fail", "failed", "blocked"]);
const blockingEvidence = entries.filter((entry: any) => entry?.blocking === true || blockingStatuses.has(String(entry?.status ?? "").toLowerCase()));
const scoreDecisionEvidence = entries.filter((entry: any) => entry?.source_type === "scoring" && entry?.score_decision);
const scoreDecisionBlocking = scoreDecisionEvidence.filter((entry: any) => entry?.score_decision?.blocking_decision === true);
const revisionLoopEvidence = entries.filter((entry: any) => entry?.source_type === "revision" && entry?.revision_loop_analysis);
const revisionLoopBlocking = revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.blocking_decision === true);
const safeStructureEvidence = entries.filter((entry: any) => entry?.source_type === "source_artifact" && entry?.safe_structure_analysis);
const safeStructureBlocking = safeStructureEvidence.filter((entry: any) => entry?.safe_structure_analysis?.blocking_decision === true);
const architectureQualityEvidence = entries.filter((entry: any) => entry?.source_type === "source_artifact" && entry?.architecture_quality_analysis);
const architectureQualityBlocking = architectureQualityEvidence.filter((entry: any) => entry?.architecture_quality_analysis?.blocking_decision === true);
const globalNormalizationEvidence = entries.filter((entry: any) => entry?.source_type === "source_artifact" && entry?.global_normalization_analysis);
const globalNormalizationBlocking = globalNormalizationEvidence.filter((entry: any) => entry?.global_normalization_analysis?.blocking_decision === true);
const promptContractEvidence = entries.filter((entry: any) => entry?.source_type === "prompt_contract" && entry?.prompt_contract_analysis);
const promptContractBlocking = promptContractEvidence.filter((entry: any) => entry?.prompt_contract_analysis?.blocking_decision === true);
const contextBundleEvidence = entries.filter((entry: any) => entry?.source_type === "context" && entry?.context_bundle);
const contextBundleBlocking = contextBundleEvidence.filter((entry: any) => entry?.context_bundle?.blocking_decision === true);
const runtimeTelemetryEvidence = entries.filter((entry: any) => entry?.runtime_telemetry);
const runtimeTelemetryBlocking = runtimeTelemetryEvidence.filter((entry: any) => entry?.runtime_telemetry?.blocking_decision === true);
const runtimeTelemetryValidationEvidence = entries.filter((entry: any) => entry?.runtime_telemetry_validation);
const runtimeTelemetryValidationBlocking = runtimeTelemetryValidationEvidence.filter((entry: any) => entry?.runtime_telemetry_validation?.blocking_decision === true);
function paths(list: any[]): string[] {
  return list.map((entry: any) => entry.path).filter((value: any) => typeof value === "string");
}
function claim(claim_id: string, claim_type: string, evidenceRefs: string[], claim_status = "supported", notApplicableReason?: string): any {
  return {
    claim_schema_version: "1.0",
    claim_id,
    claim_type,
    claim_status,
    support_mode: claim_status === "supported" ? "manifest_backed" : "not_applicable",
    evidence_refs: evidenceRefs,
    ...(notApplicableReason ? { not_applicable_reason: notApplicableReason } : {}),
  };
}
function optionalClaim(claim_id: string, claim_type: string, evidenceRefs: string[], notApplicableReason: string): any {
  return evidenceRefs.length
    ? claim(claim_id, claim_type, evidenceRefs)
    : claim(claim_id, claim_type, [], "not_applicable", notApplicableReason);
}
const allEvidenceRefs = paths(entries);
const reportClaims = [
  claim("evidence_manifest_validated", "manifest_integrity", allEvidenceRefs),
  optionalClaim("validation_summary_backed", "validation", paths(entries.filter((entry: any) => entry.source_type === "validation")), "No validation evidence entries were present in the evidence manifest."),
  optionalClaim("score_decision_summary_backed", "scoring", paths(scoreDecisionEvidence), "No score decision artifact was present in the evidence manifest."),
  optionalClaim("revision_loop_summary_backed", "revision", paths(revisionLoopEvidence), "No revision loop analysis artifact was present in the evidence manifest."),
  optionalClaim("safe_structure_summary_backed", "safe_structure", paths(safeStructureEvidence), "No safe structure analysis artifact was present in the evidence manifest."),
  optionalClaim("architecture_quality_summary_backed", "architecture_quality", paths(architectureQualityEvidence), "No architecture quality analysis artifact was present in the evidence manifest."),
  optionalClaim("global_normalization_summary_backed", "global_normalization", paths(globalNormalizationEvidence), "No global normalization analysis artifact was present in the evidence manifest."),
  optionalClaim("prompt_contract_summary_backed", "prompt_contract", paths(promptContractEvidence), "No prompt contract analysis artifact was present in the evidence manifest."),
  optionalClaim("context_bundle_summary_backed", "context", paths(contextBundleEvidence), "No compiled context bundle or context-load trace artifact was present in the evidence manifest."),
  optionalClaim("runtime_telemetry_summary_backed", "telemetry", paths(runtimeTelemetryEvidence), "No runtime telemetry artifact was present in the evidence manifest."),
  optionalClaim("runtime_telemetry_validation_backed", "telemetry_validation", paths(runtimeTelemetryValidationEvidence), "No runtime telemetry validation artifact was present in the evidence manifest."),
  optionalClaim("transition_evidence_backed", "transition", paths(entries.filter((entry: any) => ["gate", "handoff", "revision"].includes(String(entry.source_type)))), "No gate, handoff, or revision transition evidence was present in the evidence manifest."),
];
const reportClaimsById = new Map(reportClaims.map((entry: any) => [String(entry.claim_id), entry]));
function claimBackedNarrativeSection(sectionId: string, title: string, sourceClaimId: string, supportedText: string, notApplicableText: string): any {
  const sourceClaim = reportClaimsById.get(sourceClaimId);
  const claimStatus = String(sourceClaim?.claim_status ?? "unsupported");
  const evidenceRefs = claimStatus === "supported" && Array.isArray(sourceClaim?.evidence_refs) ? sourceClaim.evidence_refs : [];
  return {
    section_schema_version: "1.0",
    section_id: sectionId,
    title,
    generated_from: "report_claim",
    source_claim_id: sourceClaimId,
    claim_status: claimStatus,
    support_mode: sourceClaim?.support_mode ?? null,
    evidence_refs: evidenceRefs,
    summary_text: claimStatus === "supported" ? supportedText : notApplicableText,
  };
}
const narrativeSummary = {
  narrative_schema_version: "1.0",
  generated_from_report_claims: true,
  freeform_narrative_allowed: false,
  sections: [
    claimBackedNarrativeSection("evidence_manifest", "Evidence manifest", "evidence_manifest_validated", `Final report is based on ${entries.length} manifest-backed evidence artifact(s).`, "Evidence manifest was not available for narrative summary generation."),
    claimBackedNarrativeSection("validation", "Validation evidence", "validation_summary_backed", `Validation summary is backed by ${counts.validation ?? 0} validation evidence artifact(s).`, "No validation evidence entries were present in the evidence manifest."),
    claimBackedNarrativeSection("score_decision", "Score decision evidence", "score_decision_summary_backed", `Score decision summary is backed by ${scoreDecisionEvidence.length} scoring artifact(s).`, "No score decision artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("revision_loop", "Revision loop evidence", "revision_loop_summary_backed", `Revision loop summary is backed by ${revisionLoopEvidence.length} revision analysis artifact(s).`, "No revision loop analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("safe_structure", "Safe structure evidence", "safe_structure_summary_backed", `Safe structure summary is backed by ${safeStructureEvidence.length} structure analysis artifact(s).`, "No safe structure analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("architecture_quality", "Architecture quality evidence", "architecture_quality_summary_backed", `Architecture quality summary is backed by ${architectureQualityEvidence.length} adapter-neutral architecture artifact(s).`, "No architecture quality analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("global_normalization", "Global normalization evidence", "global_normalization_summary_backed", `Global normalization summary is backed by ${globalNormalizationEvidence.length} abstract normalization artifact(s).`, "No global normalization analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("prompt_contracts", "Prompt contract evidence", "prompt_contract_summary_backed", `Prompt contract summary is backed by ${promptContractEvidence.length} prompt contract analysis artifact(s).`, "No prompt contract analysis artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("context_bundle", "Compiled context evidence", "context_bundle_summary_backed", `Compiled context summary is backed by ${contextBundleEvidence.length} context artifact(s).`, "No compiled context bundle or context-load trace artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("runtime_telemetry", "Runtime telemetry evidence", "runtime_telemetry_summary_backed", `Runtime telemetry summary is backed by ${runtimeTelemetryEvidence.length} telemetry artifact(s).`, "No runtime telemetry artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("runtime_telemetry_validation", "Runtime telemetry validation evidence", "runtime_telemetry_validation_backed", `Runtime telemetry validation summary is backed by ${runtimeTelemetryValidationEvidence.length} telemetry validation artifact(s).`, "No runtime telemetry validation artifact was present in the evidence manifest."),
    claimBackedNarrativeSection("transition", "Transition evidence", "transition_evidence_backed", "Transition evidence summary is backed by gate, handoff, or revision artifacts.", "No gate, handoff, or revision transition evidence was present in the evidence manifest."),
  ],
};
const unsupportedReportClaims = reportClaims.filter((entry: any) => {
  if (entry.claim_status === "supported") return !Array.isArray(entry.evidence_refs) || entry.evidence_refs.length === 0;
  if (entry.claim_status === "not_applicable") return typeof entry.not_applicable_reason !== "string" || !entry.not_applicable_reason.trim();
  return true;
});
for (const unsupported of unsupportedReportClaims) {
  issues.push(issue("error", "REPORT_CLAIM_UNSUPPORTED", `Final report claim is unsupported or missing evidence: ${String(unsupported.claim_id ?? "unknown_claim")}`, ".ai/reports/final-mission-report.yaml"));
}
const finalReport = {
  artifact: "final_mission_report",
  generated_by: SCRIPT_ID,
  status: issues.length || blockingEvidence.length ? "blocked" : "complete",
  summary: "Final mission report generated from typed report_claims and validated evidence_manifest_v2 artifacts.",
  summary_source: "typed_report_claims",
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_index: ".ai/reports/evidence-index.yaml",
  evidence_refs: allEvidenceRefs,
  report_claim_schema: {
    schema_version: "1.0",
    unsupported_claim_policy: "block_report_validation",
    supported_claim_count: reportClaims.filter((entry: any) => entry.claim_status === "supported").length,
    not_applicable_claim_count: reportClaims.filter((entry: any) => entry.claim_status === "not_applicable").length,
    unsupported_claim_count: unsupportedReportClaims.length,
  },
  report_claims: reportClaims,
  narrative_summary: narrativeSummary,
  evidence_counts_by_type: counts,
  evidence_manifest_summary: {
    schema_version: evidenceManifest.schema_version ?? null,
    manifest_status: evidenceManifest.status ?? null,
    evidence_count: entries.length,
    validation_status: evidenceManifest.manifest_validation?.status ?? null,
    validation_blocking: evidenceManifest.manifest_validation?.blocking === true,
  },
  validation_summary: {
    blocking_evidence_count: blockingEvidence.length,
    failed_evidence_refs: paths(blockingEvidence),
    blocking_validation_refs: paths(blockingEvidence.filter((entry: any) => entry.source_type === "validation")),
  },
  score_decision_summary: {
    score_decision_refs: paths(scoreDecisionEvidence),
    score_decision_count: scoreDecisionEvidence.length,
    blocking_score_decision_refs: paths(scoreDecisionBlocking),
    observe_mode_only: scoreDecisionEvidence.every((entry: any) => entry?.score_decision?.blocking_decision !== true),
    recommendations: scoreDecisionEvidence.map((entry: any) => ({
      source: entry.path,
      mission_mode: entry.score_decision?.mission_mode ?? null,
      deterministic_recommendation: entry.score_decision?.deterministic_recommendation ?? null,
      blocking_decision: entry.score_decision?.blocking_decision === true,
    })),
  },
  revision_loop_summary: {
    revision_loop_refs: paths(revisionLoopEvidence),
    revision_loop_count: revisionLoopEvidence.length,
    blocking_revision_loop_refs: paths(revisionLoopBlocking),
    observe_mode_only: revisionLoopEvidence.every((entry: any) => entry?.revision_loop_analysis?.blocking_decision !== true),
    repeated_fingerprint_count: revisionLoopEvidence.reduce((total: number, entry: any) => total + Number(entry?.revision_loop_analysis?.repeated_fingerprint_count ?? 0), 0),
    no_progress_suspected_count: revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.no_progress_suspected === true).length,
    analyses: revisionLoopEvidence.map((entry: any) => ({
      source: entry.path,
      mission_id: entry.revision_loop_analysis?.mission_id ?? null,
      active_failure_fingerprint: entry.revision_loop_analysis?.active_failure_fingerprint ?? null,
      active_fingerprint_count: entry.revision_loop_analysis?.active_fingerprint_count ?? 0,
      no_progress_suspected: entry.revision_loop_analysis?.no_progress_suspected === true,
      blocking_decision: entry.revision_loop_analysis?.blocking_decision === true,
    })),
  },
  safe_structure_summary: {
    safe_structure_refs: paths(safeStructureEvidence),
    safe_structure_count: safeStructureEvidence.length,
    blocking_safe_structure_refs: paths(safeStructureBlocking),
    observe_mode_only: safeStructureEvidence.every((entry: any) => entry?.safe_structure_analysis?.blocking_decision !== true),
    total_inbound_dependency_count: safeStructureEvidence.reduce((total: number, entry: any) => total + Number(entry?.safe_structure_analysis?.inbound_dependency_count ?? 0), 0),
    warning_codes: Array.from(new Set(safeStructureEvidence.flatMap((entry: any) => Array.isArray(entry?.safe_structure_analysis?.warning_codes) ? entry.safe_structure_analysis.warning_codes : []))).sort(),
    analyses: safeStructureEvidence.map((entry: any) => ({
      source: entry.path,
      change_kind: entry.safe_structure_analysis?.change_kind ?? null,
      candidate_file: entry.safe_structure_analysis?.candidate_file ?? null,
      target_file: entry.safe_structure_analysis?.target_file ?? null,
      inbound_dependency_count: entry.safe_structure_analysis?.inbound_dependency_count ?? 0,
      outbound_dependency_count: entry.safe_structure_analysis?.outbound_dependency_count ?? 0,
      warning_codes: entry.safe_structure_analysis?.warning_codes ?? [],
      blocking_decision: entry.safe_structure_analysis?.blocking_decision === true,
    })),
  },
  architecture_quality_summary: {
    architecture_quality_refs: paths(architectureQualityEvidence),
    architecture_quality_count: architectureQualityEvidence.length,
    blocking_architecture_quality_refs: paths(architectureQualityBlocking),
    observe_mode_only: architectureQualityEvidence.every((entry: any) => entry?.architecture_quality_analysis?.blocking_decision !== true),
    adapter_neutral_core: architectureQualityEvidence.every((entry: any) => entry?.architecture_quality_analysis?.adapter_neutral === true),
    total_quality_dimension_count: architectureQualityEvidence.reduce((total: number, entry: any) => total + Number(entry?.architecture_quality_analysis?.quality_dimension_count ?? 0), 0),
    warning_codes: Array.from(new Set(architectureQualityEvidence.flatMap((entry: any) => Array.isArray(entry?.architecture_quality_analysis?.warning_codes) ? entry.architecture_quality_analysis.warning_codes : []))).sort(),
    analyses: architectureQualityEvidence.map((entry: any) => ({
      source: entry.path,
      adapter_discovery_source: entry.architecture_quality_analysis?.adapter_discovery_source ?? null,
      adapter_neutral: entry.architecture_quality_analysis?.adapter_neutral === true,
      language_adapter_count: entry.architecture_quality_analysis?.language_adapter_count ?? 0,
      framework_adapter_count: entry.architecture_quality_analysis?.framework_adapter_count ?? 0,
      quality_dimension_count: entry.architecture_quality_analysis?.quality_dimension_count ?? 0,
      warning_codes: entry.architecture_quality_analysis?.warning_codes ?? [],
      blocking_decision: entry.architecture_quality_analysis?.blocking_decision === true,
    })),
  },
  global_normalization_summary: {
    global_normalization_refs: paths(globalNormalizationEvidence),
    global_normalization_count: globalNormalizationEvidence.length,
    blocking_global_normalization_refs: paths(globalNormalizationBlocking),
    observe_mode_only: globalNormalizationEvidence.every((entry: any) => entry?.global_normalization_analysis?.blocking_decision !== true),
    adapter_neutral_core: globalNormalizationEvidence.every((entry: any) => entry?.global_normalization_analysis?.adapter_neutral === true),
    abstract_policy_only: globalNormalizationEvidence.every((entry: any) => entry?.global_normalization_analysis?.policy_abstraction === "universal_normalization_dimensions" && entry?.global_normalization_analysis?.concrete_signals_are_policy === false),
    mutation_allowed: globalNormalizationEvidence.some((entry: any) => entry?.global_normalization_analysis?.mutation_allowed === true),
    total_normalization_dimension_count: globalNormalizationEvidence.reduce((total: number, entry: any) => total + Number(entry?.global_normalization_analysis?.normalization_dimension_count ?? 0), 0),
    warning_codes: Array.from(new Set(globalNormalizationEvidence.flatMap((entry: any) => Array.isArray(entry?.global_normalization_analysis?.warning_codes) ? entry.global_normalization_analysis.warning_codes : []))).sort(),
    analyses: globalNormalizationEvidence.map((entry: any) => ({
      source: entry.path,
      policy_abstraction: entry.global_normalization_analysis?.policy_abstraction ?? null,
      adapter_neutral: entry.global_normalization_analysis?.adapter_neutral === true,
      concrete_signals_are_policy: entry.global_normalization_analysis?.concrete_signals_are_policy === true,
      project_specific_rules_allowed: entry.global_normalization_analysis?.project_specific_rules_allowed === true,
      mutation_allowed: entry.global_normalization_analysis?.mutation_allowed === true,
      normalization_dimension_count: entry.global_normalization_analysis?.normalization_dimension_count ?? 0,
      detector_signal_keys: entry.global_normalization_analysis?.detector_signal_keys ?? [],
      finding_keys: entry.global_normalization_analysis?.finding_keys ?? [],
      warning_codes: entry.global_normalization_analysis?.warning_codes ?? [],
      blocking_decision: entry.global_normalization_analysis?.blocking_decision === true,
    })),
  },

  prompt_contract_summary: {
    prompt_contract_refs: paths(promptContractEvidence),
    prompt_contract_count: promptContractEvidence.length,
    blocking_prompt_contract_refs: paths(promptContractBlocking),
    observe_mode_only: promptContractEvidence.every((entry: any) => entry?.prompt_contract_analysis?.blocking_decision !== true),
    mutation_allowed: promptContractEvidence.some((entry: any) => entry?.prompt_contract_analysis?.mutation_allowed === true),
    prompt_rewrite_allowed: promptContractEvidence.some((entry: any) => entry?.prompt_contract_analysis?.prompt_rewrite_allowed === true),
    total_prompt_surface_count: promptContractEvidence.reduce((total: number, entry: any) => total + Number(entry?.prompt_contract_analysis?.prompt_surface_count ?? 0), 0),
    total_missing_sections: promptContractEvidence.reduce((total: number, entry: any) => total + Number(entry?.prompt_contract_analysis?.total_missing_sections ?? 0), 0),
    total_complete_contract_surfaces: promptContractEvidence.reduce((total: number, entry: any) => total + Number(entry?.prompt_contract_analysis?.surfaces_with_complete_contract ?? 0), 0),
    analyses: promptContractEvidence.map((entry: any) => ({
      source: entry.path,
      rollout_mode: entry.prompt_contract_analysis?.rollout_mode ?? null,
      enforcement_mode: entry.prompt_contract_analysis?.enforcement_mode ?? null,
      prompt_surface_count: entry.prompt_contract_analysis?.prompt_surface_count ?? 0,
      surfaces_with_complete_contract: entry.prompt_contract_analysis?.surfaces_with_complete_contract ?? 0,
      total_missing_sections: entry.prompt_contract_analysis?.total_missing_sections ?? 0,
      required_sections: entry.prompt_contract_analysis?.required_sections ?? [],
      missing_sections_behavior: entry.prompt_contract_analysis?.missing_sections_behavior ?? null,
      unknown_route_behavior: entry.prompt_contract_analysis?.unknown_route_behavior ?? null,
      direct_script_reference_behavior: entry.prompt_contract_analysis?.direct_script_reference_behavior ?? null,
      blocking_decision: entry.prompt_contract_analysis?.blocking_decision === true,
    })),
  },

  context_bundle_summary: {
    context_bundle_refs: paths(contextBundleEvidence),
    context_bundle_count: contextBundleEvidence.length,
    blocking_context_bundle_refs: paths(contextBundleBlocking),
    observe_mode_only: contextBundleEvidence.every((entry: any) => entry?.context_bundle?.blocking_decision !== true),
    mutation_allowed: contextBundleEvidence.some((entry: any) => entry?.context_bundle?.mutation_allowed === true),
    total_included_route_count: contextBundleEvidence.reduce((total: number, entry: any) => total + Number(entry?.context_bundle?.included_route_count ?? 0), 0),
    total_included_artifact_count: contextBundleEvidence.reduce((total: number, entry: any) => total + Number(entry?.context_bundle?.included_artifact_count ?? 0), 0),
    total_retrieval_trace_count: contextBundleEvidence.reduce((total: number, entry: any) => total + Number(entry?.context_bundle?.retrieval_trace_count ?? 0), 0),
    scopes: Array.from(new Set(contextBundleEvidence.map((entry: any) => entry?.context_bundle?.scope).filter((value: any) => typeof value === "string"))).sort(),
    analyses: contextBundleEvidence.map((entry: any) => ({
      source: entry.path,
      scope: entry.context_bundle?.scope ?? null,
      enforcement_mode: entry.context_bundle?.enforcement_mode ?? null,
      mutation_allowed: entry.context_bundle?.mutation_allowed === true,
      selected_workflow_lanes: entry.context_bundle?.selected_workflow_lanes ?? [],
      selection_source: entry.context_bundle?.selection_source ?? null,
      adapter_discovery_source: entry.context_bundle?.adapter_discovery_source ?? null,
      included_route_count: entry.context_bundle?.included_route_count ?? 0,
      included_artifact_count: entry.context_bundle?.included_artifact_count ?? 0,
      retrieval_trace_count: entry.context_bundle?.retrieval_trace_count ?? 0,
      adapter_topology_present: entry.context_bundle?.adapter_topology_present === true,
      prompt_contract_analysis_present: entry.context_bundle?.prompt_contract_analysis_present === true,
      blocking_decision: entry.context_bundle?.blocking_decision === true,
    })),
  },

  runtime_telemetry_summary: {
    runtime_telemetry_refs: paths(runtimeTelemetryEvidence),
    runtime_telemetry_count: runtimeTelemetryEvidence.length,
    blocking_runtime_telemetry_refs: paths(runtimeTelemetryBlocking),
    observe_mode_only: runtimeTelemetryEvidence.every((entry: any) => entry?.runtime_telemetry?.blocking_decision !== true),
    mutation_allowed: runtimeTelemetryEvidence.some((entry: any) => entry?.runtime_telemetry?.mutation_allowed === true),
    total_event_count: runtimeTelemetryEvidence.reduce((total: number, entry: any) => total + Number(entry?.runtime_telemetry?.event_count ?? 0), 0),
    total_blocking_event_count: runtimeTelemetryEvidence.reduce((total: number, entry: any) => total + Number(entry?.runtime_telemetry?.blocking_event_count ?? 0), 0),
    total_warning_event_count: runtimeTelemetryEvidence.reduce((total: number, entry: any) => total + Number(entry?.runtime_telemetry?.warning_event_count ?? 0), 0),
    total_error_event_count: runtimeTelemetryEvidence.reduce((total: number, entry: any) => total + Number(entry?.runtime_telemetry?.error_event_count ?? 0), 0),
    event_type_keys: Array.from(new Set(runtimeTelemetryEvidence.flatMap((entry: any) => Array.isArray(entry?.runtime_telemetry?.event_type_keys) ? entry.runtime_telemetry.event_type_keys : []))).sort(),
    route_event_keys: Array.from(new Set(runtimeTelemetryEvidence.flatMap((entry: any) => Array.isArray(entry?.runtime_telemetry?.route_event_keys) ? entry.runtime_telemetry.route_event_keys : []))).sort(),
    analyses: runtimeTelemetryEvidence.map((entry: any) => ({
      source: entry.path,
      artifact_kind: entry.runtime_telemetry?.artifact_kind ?? null,
      rollout_mode: entry.runtime_telemetry?.rollout_mode ?? null,
      enforcement_mode: entry.runtime_telemetry?.enforcement_mode ?? null,
      mutation_allowed: entry.runtime_telemetry?.mutation_allowed === true,
      event_count: entry.runtime_telemetry?.event_count ?? 0,
      blocking_event_count: entry.runtime_telemetry?.blocking_event_count ?? 0,
      warning_event_count: entry.runtime_telemetry?.warning_event_count ?? 0,
      error_event_count: entry.runtime_telemetry?.error_event_count ?? 0,
      source_path_count: entry.runtime_telemetry?.source_path_count ?? 0,
      event_type_keys: entry.runtime_telemetry?.event_type_keys ?? [],
      route_event_keys: entry.runtime_telemetry?.route_event_keys ?? [],
      blocking_decision: entry.runtime_telemetry?.blocking_decision === true,
    })),
  },
  runtime_telemetry_validation_summary: {
    runtime_telemetry_validation_refs: paths(runtimeTelemetryValidationEvidence),
    runtime_telemetry_validation_count: runtimeTelemetryValidationEvidence.length,
    blocking_runtime_telemetry_validation_refs: paths(runtimeTelemetryValidationBlocking),
    shape_and_coverage_only: runtimeTelemetryValidationEvidence.every((entry: any) => entry?.runtime_telemetry_validation?.validation_scope === "shape_and_coverage_only"),
    workflow_policy_enforced: runtimeTelemetryValidationEvidence.some((entry: any) => entry?.runtime_telemetry_validation?.workflow_policy_enforced === true),
    total_validated_event_count: runtimeTelemetryValidationEvidence.reduce((total: number, entry: any) => total + Number(entry?.runtime_telemetry_validation?.event_count ?? 0), 0),
    validation_statuses: Array.from(new Set(runtimeTelemetryValidationEvidence.map((entry: any) => entry?.runtime_telemetry_validation?.status).filter((value: any) => typeof value === "string"))).sort(),
    validation_result_statuses: Array.from(new Set(runtimeTelemetryValidationEvidence.map((entry: any) => entry?.runtime_telemetry_validation?.validation_result_status).filter((value: any) => typeof value === "string"))).sort(),
    analyses: runtimeTelemetryValidationEvidence.map((entry: any) => ({
      source: entry.path,
      artifact_kind: entry.runtime_telemetry_validation?.artifact_kind ?? null,
      route_id: entry.runtime_telemetry_validation?.route_id ?? null,
      validation_scope: entry.runtime_telemetry_validation?.validation_scope ?? null,
      workflow_policy_enforced: entry.runtime_telemetry_validation?.workflow_policy_enforced === true,
      event_count: entry.runtime_telemetry_validation?.event_count ?? 0,
      status: entry.runtime_telemetry_validation?.status ?? null,
      validation_result_status: entry.runtime_telemetry_validation?.validation_result_status ?? null,
      validation_result_severity: entry.runtime_telemetry_validation?.validation_result_severity ?? null,
      blocking_decision: entry.runtime_telemetry_validation?.blocking_decision === true,
    })),
  },
  transition_evidence: {
    gates: paths(entries.filter((entry: any) => entry.source_type === "gate")),
    handoffs: paths(entries.filter((entry: any) => entry.source_type === "handoff")),
    revisions: paths(entries.filter((entry: any) => entry.source_type === "revision")),
  },
  unresolved_issues: blockingEvidence.map((entry: any) => ({ source: entry.path, status: entry.status, blocking: entry.blocking === true })),
};

writeYamlFile(path.join(root, ".ai", "reports", "final-mission-report.yaml"), finalReport);
writeYamlFile(path.join(root, ".ai", "reports", "mission-evidence-summary.yaml"), {
  artifact: "mission_evidence_summary",
  generated_by: SCRIPT_ID,
  status: finalReport.status,
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_counts_by_type: counts,
  evidence_manifest_summary: finalReport.evidence_manifest_summary,
  report_claim_count: finalReport.report_claims.length,
  narrative_summary_section_count: finalReport.narrative_summary.sections.length,
});

finish(SCRIPT_ID, issues, [".ai/reports/final-mission-report.yaml", ".ai/reports/mission-evidence-summary.yaml"], {
  status: finalReport.status,
  evidence_manifest: ".ai/reports/evidence-manifest.yaml",
  evidence_count: entries.length,
});
