import fs from "node:fs";
import path from "node:path";
import { finish, issue, readYamlFile, resolveConventionsRoot, writeYamlFile, type Issue } from "./lib/common.js";

const SCRIPT_ID = "generate-final-mission-report";
const root = resolveConventionsRoot();
const issues: Issue[] = [];
const evidencePath = path.join(root, ".ai", "reports", "evidence-index.yaml");

let evidenceIndex: any = { entries: [] };
if (!fs.existsSync(evidencePath)) {
  issues.push(issue("critical", "EVIDENCE_INDEX_MISSING", "Cannot generate final mission report without evidence-index.yaml; run collect_evidence first."));
} else {
  evidenceIndex = readYamlFile(evidencePath);
  if (evidenceIndex.generated_by !== "collect-evidence") {
    issues.push(issue("error", "EVIDENCE_INDEX_NOT_SCRIPT_PRODUCED", "Final mission report requires an evidence index generated by collect-evidence."));
  }
  if (!Array.isArray(evidenceIndex.entries)) {
    issues.push(issue("error", "EVIDENCE_INDEX_ENTRIES_INVALID", "Evidence index entries must be a list."));
    evidenceIndex.entries = [];
  }
}

const entries = Array.isArray(evidenceIndex.entries) ? evidenceIndex.entries : [];
const counts: Record<string, number> = {};
for (const entry of entries) {
  const type = String(entry?.source_type ?? "unknown");
  counts[type] = (counts[type] ?? 0) + 1;
}

const blockingStatuses = new Set(["fail", "failed", "blocked"]);
const blockingEvidence = entries.filter((entry: any) => entry?.blocking === true || blockingStatuses.has(String(entry?.status ?? "").toLowerCase()));
const scoreDecisionEvidence = entries.filter((entry: any) => entry?.source_type === "scoring" && entry?.score_decision);
const scoreDecisionBlocking = scoreDecisionEvidence.filter((entry: any) => entry?.score_decision?.blocking_decision === true);
const revisionLoopEvidence = entries.filter((entry: any) => entry?.source_type === "revision" && entry?.revision_loop_analysis);
const revisionLoopBlocking = revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.blocking_decision === true);
const finalReport = {
  artifact: "final_mission_report",
  generated_by: SCRIPT_ID,
  status: issues.length || blockingEvidence.length ? "blocked" : "complete",
  summary: "Final mission report generated from script-produced evidence artifacts.",
  evidence_index: ".ai/reports/evidence-index.yaml",
  evidence_refs: entries.map((entry: any) => entry.path).filter((value: any) => typeof value === "string"),
  evidence_counts_by_type: counts,
  validation_summary: {
    blocking_evidence_count: blockingEvidence.length,
    failed_evidence_refs: blockingEvidence.map((entry: any) => entry.path),
    blocking_validation_refs: blockingEvidence.filter((entry: any) => entry.source_type === "validation").map((entry: any) => entry.path),
  },
  score_decision_summary: {
    score_decision_refs: scoreDecisionEvidence.map((entry: any) => entry.path),
    score_decision_count: scoreDecisionEvidence.length,
    blocking_score_decision_refs: scoreDecisionBlocking.map((entry: any) => entry.path),
    observe_mode_only: scoreDecisionEvidence.every((entry: any) => entry?.score_decision?.blocking_decision !== true),
    recommendations: scoreDecisionEvidence.map((entry: any) => ({
      source: entry.path,
      mission_mode: entry.score_decision?.mission_mode ?? null,
      deterministic_recommendation: entry.score_decision?.deterministic_recommendation ?? null,
      blocking_decision: entry.score_decision?.blocking_decision === true,
    })),
  },
  revision_loop_summary: {
    revision_loop_refs: revisionLoopEvidence.map((entry: any) => entry.path),
    revision_loop_count: revisionLoopEvidence.length,
    blocking_revision_loop_refs: revisionLoopBlocking.map((entry: any) => entry.path),
    observe_mode_only: revisionLoopEvidence.every((entry: any) => entry?.revision_loop_analysis?.blocking_decision !== true),
    repeated_fingerprint_count: revisionLoopEvidence.reduce((total: number, entry: any) => total + Number(entry?.revision_loop_analysis?.repeated_fingerprint_count ?? 0), 0),
    no_progress_suspected_count: revisionLoopEvidence.filter((entry: any) => entry?.revision_loop_analysis?.no_progress_suspected === true).length,
    analyses: revisionLoopEvidence.map((entry: any) => ({
      source: entry.path,
      mission_id: entry.revision_loop_analysis?.mission_id ?? null,
      active_failure_fingerprint: entry.revision_loop_analysis?.active_failure_fingerprint ?? null,
      active_fingerprint_count: entry.revision_loop_analysis?.active_fingerprint_count ?? 0,
      no_progress_suspected: entry.revision_loop_analysis?.no_progress_suspected === true,
      blocking_decision: entry.revision_loop_analysis?.blocking_decision === true,
    })),
  },
  transition_evidence: {
    gates: entries.filter((entry: any) => entry.source_type === "gate").map((entry: any) => entry.path),
    handoffs: entries.filter((entry: any) => entry.source_type === "handoff").map((entry: any) => entry.path),
    revisions: entries.filter((entry: any) => entry.source_type === "revision").map((entry: any) => entry.path),
  },
  unresolved_issues: blockingEvidence.map((entry: any) => ({ source: entry.path, status: entry.status, blocking: entry.blocking === true })),
};

writeYamlFile(path.join(root, ".ai", "reports", "final-mission-report.yaml"), finalReport);
writeYamlFile(path.join(root, ".ai", "reports", "mission-evidence-summary.yaml"), {
  artifact: "mission_evidence_summary",
  generated_by: SCRIPT_ID,
  status: finalReport.status,
  evidence_counts_by_type: counts,
  evidence_index: ".ai/reports/evidence-index.yaml",
});

finish(SCRIPT_ID, issues, [".ai/reports/final-mission-report.yaml", ".ai/reports/mission-evidence-summary.yaml"], {
  status: finalReport.status,
  evidence_count: entries.length,
});
