import fs from "node:fs";
import path from "node:path";
import { buildUniversalValidationResult, finish, issue, readYamlFile, resolveConventionsRoot, writeYamlFile, type Issue } from "./lib/common.js";

const SCRIPT_ID = "validate-report-evidence";
const root = resolveConventionsRoot();
const issues: Issue[] = [];
const manifestPath = path.join(root, ".ai", "reports", "evidence-manifest.yaml");
const indexPath = path.join(root, ".ai", "reports", "evidence-index.yaml");

let evidenceEntries: any[] = [];
if (!fs.existsSync(manifestPath)) {
  issues.push(issue("critical", "EVIDENCE_MANIFEST_MISSING", "Evidence manifest is missing; run collect_evidence before validating report evidence."));
} else {
  const manifest = readYamlFile(manifestPath);
  if (manifest.artifact !== "evidence_manifest_v2" || manifest.schema_version !== "2.0") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_SCHEMA_INVALID", "Evidence manifest must use evidence_manifest_v2 schema_version 2.0.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (manifest.generated_by !== "collect-evidence") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_NOT_SCRIPT_PRODUCED", "Evidence manifest must be generated by collect-evidence.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!manifest.manifest_validation || typeof manifest.manifest_validation !== "object") {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_MISSING", "Evidence manifest must include manifest_validation universal result.", ".ai/reports/evidence-manifest.yaml"));
  } else if (manifest.manifest_validation.blocking === true || ["failed", "blocked"].includes(String(manifest.manifest_validation.status ?? ""))) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_VALIDATION_FAILED", "Evidence manifest validation status must be non-blocking before reports consume it.", ".ai/reports/evidence-manifest.yaml"));
  }
  if (!Array.isArray(manifest.entries)) {
    issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRIES_INVALID", "Evidence manifest entries must be a list.", ".ai/reports/evidence-manifest.yaml"));
  } else {
    evidenceEntries = manifest.entries;
    for (const entry of manifest.entries) {
      const entryPath = String(entry?.path ?? "");
      if (entry?.manifest_entry_schema !== "evidence_manifest_v2_entry") {
        issues.push(issue("error", "EVIDENCE_MANIFEST_ENTRY_SCHEMA_INVALID", `Evidence entry must use evidence_manifest_v2_entry: ${entryPath}`));
      }
      if (!entryPath.startsWith(".ai/")) {
        issues.push(issue("error", "EVIDENCE_ENTRY_PATH_INVALID", `Evidence entry path must be a .ai artifact path: ${entryPath}`));
        continue;
      }
      if (!fs.existsSync(path.join(root, entryPath))) {
        issues.push(issue("error", "EVIDENCE_ENTRY_TARGET_MISSING", `Evidence entry target does not exist: ${entryPath}`));
      }
      if (typeof entry?.content_sha256 !== "string" || !/^[a-f0-9]{64}$/.test(entry.content_sha256)) {
        issues.push(issue("error", "EVIDENCE_ENTRY_HASH_INVALID", `Evidence entry must include a sha256 hash: ${entryPath}`));
      }
      if (!entry.generated_by || String(entry.generated_by) === "unknown") {
        issues.push(issue("warning", "EVIDENCE_ENTRY_GENERATOR_UNKNOWN", `Evidence entry does not identify a script generator: ${entryPath}`));
      }
    }
  }
}

if (fs.existsSync(indexPath)) {
  const index = readYamlFile(indexPath);
  if (index.evidence_manifest !== ".ai/reports/evidence-manifest.yaml") {
    issues.push(issue("warning", "EVIDENCE_INDEX_NOT_LINKED_TO_MANIFEST", "Legacy evidence index should link to evidence-manifest.yaml.", ".ai/reports/evidence-index.yaml"));
  }
}

const reportDir = path.join(root, ".ai", "reports");
const reportFiles = fs.existsSync(reportDir)
  ? fs.readdirSync(reportDir).filter(name => name.endsWith(".yaml") || name.endsWith(".yml"))
  : [];
const evidencePathSet = new Set(evidenceEntries.map((entry: any) => String(entry?.path ?? "")).filter(Boolean));
for (const name of reportFiles) {
  if (["evidence-index.yaml", "evidence-manifest.yaml", "evidence-collection-report.yaml", "report-evidence-validation.yaml"].includes(name)) continue;
  const reportPath = path.join(reportDir, name);
  const report = readYamlFile(reportPath);
  const relative = `.ai/reports/${name}`;
  if (relative === ".ai/reports/final-mission-report.yaml") {
    if (report.generated_by !== "generate-final-mission-report") {
      issues.push(issue("error", "FINAL_REPORT_NOT_SCRIPT_PRODUCED", "Final mission report must be generated by generate-final-mission-report.", relative));
    }
    if (report.evidence_manifest !== ".ai/reports/evidence-manifest.yaml") {
      issues.push(issue("error", "FINAL_REPORT_MANIFEST_REF_MISSING", "Final mission report must reference evidence-manifest.yaml.", relative));
    }
  }
  if (report.generated_by && Array.isArray(report.evidence_refs)) {
    for (const ref of report.evidence_refs) {
      if (typeof ref !== "string" || !ref.startsWith(".ai/")) {
        issues.push(issue("error", "REPORT_EVIDENCE_REF_INVALID", `Report evidence reference must be a .ai path: ${String(ref)}`, relative));
      } else if (!fs.existsSync(path.join(root, ref))) {
        issues.push(issue("error", "REPORT_EVIDENCE_REF_MISSING", `Report evidence reference does not exist: ${ref}`, relative));
      } else if (evidenceEntries.length && !evidencePathSet.has(ref)) {
        issues.push(issue("error", "REPORT_EVIDENCE_REF_NOT_IN_MANIFEST", `Report evidence reference is not listed in evidence_manifest_v2: ${ref}`, relative));
      }
    }
  }
}

const validationResult = buildUniversalValidationResult(SCRIPT_ID, issues, {
  evidence: evidenceEntries.map((entry: any) => ({ evidence_type: "runtime_artifact", path: entry.path, source_type: entry.source_type, content_sha256: entry.content_sha256 })),
  summary: {
    evidence_manifest: fs.existsSync(manifestPath),
    evidence_count: evidenceEntries.length,
    checked_report_count: reportFiles.length,
  },
});
const validationReport = {
  artifact: "report_evidence_validation_report",
  generated_by: SCRIPT_ID,
  status: issues.some(i => i.severity === "error" || i.severity === "critical") ? "fail" : "pass",
  checked_evidence_manifest: fs.existsSync(manifestPath),
  checked_evidence_index: fs.existsSync(indexPath),
  checked_report_count: reportFiles.length,
  validation_result: validationResult,
};
writeYamlFile(path.join(root, ".ai", "reports", "report-evidence-validation.yaml"), validationReport);

finish(SCRIPT_ID, issues, [".ai/validation/validate-report-evidence.result.yaml", ".ai/reports/report-evidence-validation.yaml"], validationReport);
