import fs from "node:fs";
import path from "node:path";
import { finish, getArg, issue, readYamlFile, resolveConventionsRoot, type Issue } from "./lib/common.js";

const SCRIPT_ID = "validate-handoff";
const root = resolveConventionsRoot();
const handoffRel = getArg("handoff");
const issues: Issue[] = [];

if (!handoffRel) {
  issues.push(issue("error", "HANDOFF_INPUT_MISSING", "Handoff validation requires --handoff."));
} else if (!fs.existsSync(path.join(root, handoffRel))) {
  issues.push(issue("error", "HANDOFF_PACKET_MISSING", "Handoff packet does not exist.", handoffRel));
} else {
  try {
    const handoff = readYamlFile(path.join(root, handoffRel));
    if (handoff.artifact !== "agent_handoff_packet") issues.push(issue("error", "HANDOFF_ARTIFACT_INVALID", "Handoff artifact field must be agent_handoff_packet.", handoffRel));
    if (handoff.generated_by !== "prepare-agent-handoff") issues.push(issue("error", "HANDOFF_NOT_SCRIPT_PRODUCED", "Handoff packet must be generated by prepare-agent-handoff; agents may not manually author handoff packets.", handoffRel));
    if (handoff.status !== "prepared") issues.push(issue("error", "HANDOFF_STATUS_INVALID", "Handoff status must be prepared before downstream consumption.", handoffRel));
    if (!handoff.source_output) issues.push(issue("error", "HANDOFF_SOURCE_OUTPUT_REF_MISSING", "Handoff must include source_output.", handoffRel));
    if (!handoff.target_agent) issues.push(issue("error", "HANDOFF_TARGET_AGENT_REF_MISSING", "Handoff must include target_agent.", handoffRel));
    if (!Array.isArray(handoff.evidence_refs) || handoff.evidence_refs.length === 0) issues.push(issue("error", "HANDOFF_EVIDENCE_REFS_MISSING", "Handoff must include evidence_refs.", handoffRel));
    for (const ref of Array.isArray(handoff.evidence_refs) ? handoff.evidence_refs : []) {
      if (typeof ref === "string" && !fs.existsSync(path.join(root, ref))) {
        issues.push(issue("error", "HANDOFF_EVIDENCE_REF_MISSING", "Handoff evidence reference does not exist.", handoffRel, { ref }));
      }
    }
  } catch (error) {
    issues.push(issue("error", "HANDOFF_PACKET_UNREADABLE", "Handoff packet could not be parsed.", handoffRel, { error: String(error) }));
  }
}

finish(SCRIPT_ID, issues, [".ai/validation/validate-handoff.result.yaml"], { handoff: handoffRel ?? null });
